import { Metadata } from 'next';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import { Bot, Code2, Search, List, FolderTree, FileCode, Terminal, ArrowRight } from 'lucide-react';
import Link from 'next/link';
import McpCopyButton from './McpCopyButton';
import { codeToHtml } from 'shiki';

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://docs.lobstr.io';
const MCP_URL = `${BASE_URL}/api/mcp`;

export const metadata: Metadata = {
  title: 'MCP Server - lobstr.io API Documentation',
  description: 'Connect AI assistants to lobstr.io API documentation using the Model Context Protocol (MCP). Search docs, get code examples, and explore scrapers programmatically.',
};

const TOOLS = [
  { name: 'list_docs', description: 'Browse all core API documentation pages with category filtering and pagination.', icon: List },
  { name: 'list_examples', description: 'View all 31 scrapers with example documentation and their available endpoints.', icon: FolderTree },
  { name: 'get_doc', description: 'Get full endpoint documentation including request body, response fields, and code examples.', icon: FileCode },
  { name: 'search_docs', description: 'Keyword search across all documentation — titles, descriptions, and endpoint paths.', icon: Search },
  { name: 'get_code_example', description: 'Get cURL, Python, or API response examples for any endpoint.', icon: Code2 },
  { name: 'get_navigation', description: 'Get the full sidebar navigation structure showing how docs are organized.', icon: Bot },
];

function getPlatforms() {
  return [
    {
      name: 'Claude Code',
      config: `claude mcp add lobstrio-docs \\\n  --transport http \\\n  ${MCP_URL}`,
      lang: 'bash',
    },
    {
      name: 'Claude Desktop',
      config: JSON.stringify({ mcpServers: { 'lobstrio-docs': { type: 'http', url: MCP_URL } } }, null, 2),
      lang: 'json',
    },
    {
      name: 'Cursor',
      config: JSON.stringify({ mcpServers: { 'lobstrio-docs': { type: 'http', url: MCP_URL } } }, null, 2),
      lang: 'json',
      file: '.cursor/mcp.json',
    },
    {
      name: 'Any MCP Client',
      config: `curl -X POST ${MCP_URL} \\
  -H "Content-Type: application/json" \\
  -d '{
    "jsonrpc": "2.0",
    "method": "tools/call",
    "params": {
      "name": "search_docs",
      "arguments": { "query": "squid", "limit": 2 }
    },
    "id": 1
  }'

# Response:
# {
#   "jsonrpc": "2.0",
#   "id": 1,
#   "result": {
#     "content": [{
#       "type": "text",
#       "text": "Found 2 result(s) for \\"squid\\":\\n\\n1. Create Squid (POST /v1/squids)..."
#     }]
#   }
# }`,
      lang: 'bash',
    },
  ];
}

const EXAMPLE_PROMPTS = [
  'How do I create a squid and start scraping Google Maps?',
  'Show me the Python code for adding tasks to a scraper',
  'What parameters does the LinkedIn Profile Scraper accept?',
  'List all delivery configuration options (email, S3, webhook)',
  'How do I handle rate limiting in the lobstr.io API?',
];

async function highlight(code: string, lang: string) {
  // Shiki codeToHtml produces trusted output from known code strings at build time (no user input)
  return await codeToHtml(code, { lang, theme: 'github-light' });
}

// Server component that renders pre-highlighted code
async function CodeBlock({ code, lang, className }: { code: string; lang: string; className?: string }) {
  const html = await highlight(code, lang);
  return (
    <div
      className={`[&>pre]:!bg-[#F6F8FA] [&>pre]:!p-5 [&>pre]:!m-0 [&>pre]:!rounded-none [&>pre]:!text-[13px] [&>pre]:!leading-relaxed [&>pre]:!overflow-x-auto [&_code]:!text-[13px] ${className || ''}`}
      // Safe: html is generated by Shiki at build time from hardcoded code strings, not user input
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

export default async function McpPage() {
  const platforms = getPlatforms();

  return (
    <div className="min-h-screen bg-white">
      <Header />

      {/* Hero */}
      <section className="border-b border-[#E5E7EB]">
        <div className="max-w-4xl mx-auto px-6 py-20 text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-[#FEF2F2] text-[#FF0000] text-sm font-semibold mb-6">
            <Bot className="w-4 h-4" />
            Model Context Protocol
          </div>
          <h1 className="text-[42px] font-bold text-[#0A2540] leading-tight mb-5">
            Connect AI to lobstr.io docs
          </h1>
          <p className="text-lg text-[#0A2540]/70 max-w-2xl mx-auto leading-relaxed">
            Let your AI assistant search documentation, retrieve code examples, and explore scraper configurations — all through the MCP protocol. No API key required.
          </p>
          <div className="mt-8 flex items-center justify-center gap-4">
            <a href="#setup" className="inline-flex items-center gap-2 px-5 py-2.5 bg-[#FF0000] text-white rounded-lg font-semibold text-sm hover:bg-[#E60000] transition">
              Get Started <ArrowRight className="w-4 h-4" />
            </a>
            <a href="#tools" className="inline-flex items-center gap-2 px-5 py-2.5 text-[#FF0000] hover:text-white rounded-lg font-semibold text-sm border border-[#FF0000] hover:bg-[#FF0000] transition">
              View Tools
            </a>
          </div>
        </div>
      </section>

      {/* Tools */}
      <section id="tools" className="border-b border-[#E5E7EB]">
        <div className="max-w-4xl mx-auto px-6 py-16">
          <h2 className="text-[28px] font-bold text-[#0A2540] mb-2">Available Tools</h2>
          <p className="text-[#0A2540]/60 mb-10">6 tools for searching, browsing, and retrieving API documentation.</p>
          <div className="grid md:grid-cols-2 gap-4">
            {TOOLS.map((tool) => (
              <div key={tool.name} className="border border-[#E5E7EB] rounded-lg p-5 hover:border-[#FF0000]/30 transition group">
                <div className="flex items-start gap-3">
                  <div className="w-9 h-9 rounded-lg bg-[#FEF2F2] flex items-center justify-center shrink-0 group-hover:bg-[#FF0000]/10 transition">
                    <tool.icon className="w-4.5 h-4.5 text-[#FF0000]" />
                  </div>
                  <div>
                    <h3 className="font-mono text-sm font-semibold text-[#0A2540]">{tool.name}</h3>
                    <p className="text-sm text-[#0A2540]/60 mt-1 leading-relaxed">{tool.description}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Setup */}
      <section id="setup" className="border-b border-[#E5E7EB]">
        <div className="max-w-4xl mx-auto px-6 py-16">
          <h2 className="text-[28px] font-bold text-[#0A2540] mb-2">Setup</h2>
          <p className="text-[#0A2540]/60 mb-10">Connect to the lobstr.io MCP server from your preferred AI client. No authentication required.</p>

          <div className="space-y-6">
            {platforms.map((platform) => (
              <div key={platform.name} className="border border-[#E5E7EB] rounded-lg overflow-hidden">
                <div className="flex items-center justify-between px-5 py-3 bg-[#F9FAFB] border-b border-[#E5E7EB]">
                  <div className="flex items-center gap-2">
                    <Terminal className="w-4 h-4 text-[#0A2540]/50" />
                    <span className="font-semibold text-sm text-[#0A2540]">{platform.name}</span>
                  </div>
                  {platform.file && (
                    <span className="text-xs text-[#0A2540]/40 font-mono">{platform.file}</span>
                  )}
                </div>
                <div className="relative">
                  <CodeBlock code={platform.config} lang={platform.lang} />
                  <McpCopyButton text={platform.config} />
                </div>
              </div>
            ))}
          </div>

          <div className="mt-8 p-5 bg-[#FEF2F2] border border-[#FF0000]/10 rounded-lg">
            <p className="text-sm text-[#0A2540]/80">
              <span className="font-semibold text-[#FF0000]">Server URL: </span>
              <code className="bg-white px-2 py-0.5 rounded text-[13px] font-mono border border-[#E5E7EB]">
                {MCP_URL}
              </code>
            </p>
            <p className="text-sm text-[#0A2540]/60 mt-2">
              Public endpoint — no API key or OAuth required. Works with any MCP-compatible client.
            </p>
          </div>
        </div>
      </section>

      {/* Example Prompts */}
      <section id="examples" className="border-b border-[#E5E7EB]">
        <div className="max-w-4xl mx-auto px-6 py-16">
          <h2 className="text-[28px] font-bold text-[#0A2540] mb-2">Example Prompts</h2>
          <p className="text-[#0A2540]/60 mb-10">Once connected, try asking your AI assistant:</p>
          <div className="space-y-3">
            {EXAMPLE_PROMPTS.map((prompt, i) => (
              <div key={i} className="flex items-start gap-3 px-5 py-3.5 border border-[#E5E7EB] rounded-lg hover:bg-[#F9FAFB] transition">
                <span className="text-[#FF0000] font-mono text-sm font-bold mt-0.5">&gt;</span>
                <span className="text-[15px] text-[#0A2540]/80">{prompt}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* API Reference */}
      <section>
        <div className="max-w-4xl mx-auto px-6 py-16">
          <h2 className="text-[28px] font-bold text-[#0A2540] mb-2">API Reference</h2>
          <p className="text-[#0A2540]/60 mb-10">The MCP server uses JSON-RPC 2.0 over HTTP POST.</p>

          <div className="border border-[#E5E7EB] rounded-lg overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-[#F9FAFB] border-b border-[#E5E7EB]">
                  <th className="text-left px-5 py-3 font-semibold text-[#0A2540]">Method</th>
                  <th className="text-left px-5 py-3 font-semibold text-[#0A2540]">Description</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#E5E7EB]">
                <tr>
                  <td className="px-5 py-3 font-mono text-[13px] text-[#FF0000]">initialize</td>
                  <td className="px-5 py-3 text-[#0A2540]/70">Handshake — returns server info and capabilities</td>
                </tr>
                <tr>
                  <td className="px-5 py-3 font-mono text-[13px] text-[#FF0000]">tools/list</td>
                  <td className="px-5 py-3 text-[#0A2540]/70">List all available tools with input schemas</td>
                </tr>
                <tr>
                  <td className="px-5 py-3 font-mono text-[13px] text-[#FF0000]">tools/call</td>
                  <td className="px-5 py-3 text-[#0A2540]/70">Execute a tool with arguments</td>
                </tr>
              </tbody>
            </table>
          </div>

          <div className="mt-10 text-center">
            <Link href="/authentication" className="inline-flex items-center gap-2 text-sm font-semibold text-[#FF0000] hover:underline">
              Explore the full API documentation <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
